# mkapp
# ~/google_appengine/dev_appserver.py --high_replication tmp
# ~/google_appengine/appcfg.py update tmp

application: maymounkov-org
runtime: go
version: n1
api_version: go1

handlers:
- url: /\.appfs.*
  script: _go_app
  secure: always
- url: /draft(/.*)?
  script: _go_app
  login: required
- url: /admin(/.*)?
  script: _go_app
  login: admin

# MUST BE LAST
- url: /.*
  script: _go_app
